In [3]:
import pyvista
import pandas as pd
import numpy as np

In [4]:
points = np.arange(0.01, 0.2, 0.01)

pyVista_res_l2 = pd.DataFrame()
pyVista_res_l2['points'] = points
pyVista_res_l2.set_index('points', inplace = True)

pyVista_sum_l2 = pd.DataFrame()
pyVista_sum_l2['points'] = points
pyVista_sum_l2.set_index('points', inplace = True)

In [6]:
def get_sample_data(path):
    filename = '/data' + path + '.vtk'
    mesh = pyvista.read(filename)
    mesh.sample_over_line((0, -0.00227, 0.09),(0, 0.00227, 0.09))
    sample = [] 
    for i in points:
         sample.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].max())#resolution=15
    sums=[] 
    for i in points:
         sums.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].sum())#resolution=15
    return sample, sums

In [7]:

files = ['96k_cells_l2','144k_cells_l2','258k_cells_l2','500k_cells_l2']
for i in files:
    pyVista_res_l2[i], pyVista_sum_l2[i]  = get_sample_data(i)
    
#pyVista_res_l2.drop(['96k_cells'], axis=1, inplace = True)

In [11]:

pyVista_res_l2.tail(10)

        96k_cells_l2  144k_cells_l2  258k_cells_l2  500k_cells_l2
points
0.10        1.052538       1.061900       1.062951       1.066470
0.11        1.052641       1.061992       1.063046       1.066568
0.12        1.052688       1.062039       1.063089       1.066613
0.13        1.052711       1.062059       1.063111       1.066633
0.14        1.052721       1.062069       1.063121       1.066643
0.15        1.052721       1.062069       1.063126       1.066648
0.16        1.052729       1.062077       1.063127       1.066653
0.17        1.052731       1.062074       1.063127       1.066653
0.18        1.052729       1.062074       1.063128       1.066653
0.19        1.052731       1.062070       1.063129       1.066653

In [12]:
 pyVista_sum_l2.tail(10)

        96k_cells_l2  144k_cells_l2  258k_cells_l2  500k_cells_l2
points
0.10       10.411175      10.558873      10.549753      10.586522
0.11       10.411591      10.559242      10.550138      10.586921
0.12       10.411784      10.559423      10.550318      10.587097
0.13       10.411875      10.559515      10.550403      10.587173
0.14       10.411915      10.559561      10.550444      10.587217
0.15       10.411922      10.559563      10.550461      10.587239
0.16       10.411951      10.559584      10.550467      10.587251
0.17       10.411955      10.559576      10.550467      10.587252
0.18       10.411952      10.559588      10.550469      10.587253
0.19       10.411962      10.559551      10.550486      10.587262